default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: lampton_database

test:
  <<: *default
  database: lampton_database

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>